branches:
  only:
  - master

language: go

dist: xenial

go:
- "1.14.x"
- "1.15.x"

go_import_path: github.com/sylr/prometheus-azure-exporter

env:
  global:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org/
  - GITHUB_ENCRYPTED_SSH_KEY=.travis/github_deploy_key.enc
  - GITHUB_SSH_KEY=.travis/github_deploy_key

services:
- docker

install:
- true

before_install:
- openssl aes-256-cbc -K $encrypted_276fe16c3c2d_key -iv $encrypted_276fe16c3c2d_iv -in $GITHUB_ENCRYPTED_SSH_KEY -out $GITHUB_SSH_KEY -d && chmod 0600 .travis/github_deploy_key
- eval "$(ssh-agent -s)"
- ssh-add $GITHUB_SSH_KEY

script:
- gofmt -d -e -l . && git diff --quiet
- go test -v ./...
- make build
- ./prometheus-azure-exporter --version
- ./prometheus-azure-exporter --help
