name: Debug
on:
  push:
    branches: [master]
  pull_request:
jobs:
  release:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to GitHub Docker Registry
      run: docker login ghcr.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}

    - name: Build debian based docker image
      run: make docker-build

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Git diff
      run: git status && git diff
