name: Docker build
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Fetch tags
      run: |
        git fetch --unshallow origin +refs/tags/*:refs/tags/*
        git update-index --refresh
        git describe --tags

    - name: Build debian based docker image
      run: docker build . -f Dockerfile -t prometheus-azure-exporter:$(git describe --tag)-debian

    - name: Docker scratch based docker image
      run: docker build . -f Dockerfile-scratch -t prometheus-azure-exporter:$(git describe --tag)-scratch

    - run: docker images
