name: Docker release
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build debian based docker image
      run: |-
        docker build . --file Dockerfile --tag ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)-debian
        docker tag ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)-debian \
                   ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)

    - name: Build scratch based docker image
      run: docker build . --file Dockerfile-scratch --tag ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)-scratch

    - name: Login to GitHub Docker Registry
      run: docker login ghcr.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |-
        docker push ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)-debian
        docker push ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)-scratch
        docker push ghcr.io/sylr/prometheus-azure-exporter:$(git describe --tags)
