name: Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.14", "1.15.0-rc1"]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: "false"
        go-version: ${{ matrix.go }}
      id: go

    - name: Go version
      run: go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify go mod
      run: make verify-go-mod

    - name: Test
      run: make test

    - name: Build
      run: make build
