name: Release
on:
  release:
    types: [published]
jobs:
  release:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to GitHub Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Login to Quay.io docker registry
      run: docker login quay.io --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      env:
        DOCKER_USERNAME: ${{ secrets.QUAY_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_DOCKER_PASSWORD }}

    - name: Build debian based docker image
      run: make docker-build

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Build scratch based multi-arch docker image
      run: make docker-buildx-build

    - name: Push debian based docker image
      run: make docker-push

    - name: Push scratch based multi-arch docker image to quay.io
      run: |
        make docker-buildx-push DOCKER_BUILD_IMAGE=ghcr.io/sylr/prometheus-azure-exporter
        make docker-buildx-push DOCKER_BUILD_IMAGE=quay.io/sylr/prometheus-azure-exporter
